nodeid="KK"

[general]
 logdir = "./log"
 loglevel = "debug"
 nodeid = "KK"

[server]
  centralconfigserver = "localhost"
  centralconfigport = 1234
  reloadconfig = 10

[checkfiles]

[checkfiles."a"]
  filepath = "/tmp/test1.conf"
  filesum = "3029a6a3e7ea0d48f9daeb867a790b7f"
  fileowner = "developer"
  filemode = "0644"
  checkcmd = "echo \"check 1 cmd\" >> /tmp/test1.conf.cmd"
  reloadcmd = "echo \"reload 1 cmd\">> /tmp/test1.conf.cmd"
  uploadfileaftercmd= "/tmp/test1.conf.cmd"

[checkfiles."b"]
  filepath = "/tmp/test2.conf"
  filesum = "3029a6a3e7ea0d48f9daeb867a790b7f"
  fileowner = "developer"
  filemode = "0644"
  checkcmd = "echo \"check 2 cmd\" >> /tmp/test2.conf.cmd"
  reloadcmd = "echo \"reload 2 cmd\">> /tmp/test2.conf.cmd"
  uploadfileaftercmd= "/tmp/test2.conf.cmd"
